armor_detector_tensorrt:
  ros__parameters:
    use_sim_time: false
    debug_mode: false
    target_color: 0
    use_sensor_data_qos: true
    detector:
      camera_name: 'camera'
      subscribe_compressed: false
      model_path: ""   #load by launch_file
      confidence_threshold: 0.25
      top_k: 128
      nms_threshold: 0.3